#! /usr/bin/python3
# -*- coding: utf-8 -*-

#   Copyright (c) 2016 François Michel (edited by Ludovic Taffin - December 2018)
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU Affero General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU Affero General Public License for more details.
#
#   You should have received a copy of the GNU Affero General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.

import json
import subprocess
import shlex
import sys
import re
import os
from json import JSONDecodeError

from inginious import feedback
from inginious import rst
from inginious import input

if __name__ == '__main__':
    input.parse_template('template.py', 'student/exercice.py')
    resproc = subprocess.Popen(['python3', 'student/exercice.py'], universal_newlines=True,stderr=subprocess.PIPE,stdout=subprocess.PIPE)
    out,err = resproc.communicate()
    resultat = resproc.returncode
    stdout=out + str(err)
    print(resultat)
    if resultat == 127:
        feedback.set_global_result('success')
        ans = "Bravo, votre code compile.Voici la sortie de votre méthode de test:"
        if stdout != '\n':
            ans += rst.get_codeblock("",stdout)
        feedback.set_global_feedback(ans)
    elif resultat == 252:
        feedback.set_global_result('failed')
        feedback.set_global_feedback("La limite de mémoire de votre programme est dépassée")
        sys.exit(0)
    elif resultat == 253:
        feedback.set_global_result('timeout')
        feedback.set_global_feedback("La limite de temps d'exécution de votre programme est dépassée")
        sys.exit(0)
    else:
        feedback.set_global_result('failed')
        ans = "Quelque chose s'est mal déroulé."
        if stdout != '\n':
            ans += rst.get_codeblock("",stdout)
        feedback.set_global_feedback(ans)