#!/usr/bin/python3
# -*- coding: utf-8 -*-


@@q1@@


    def __str__(self):
        ans = "Etudiant {} {} né le {}, peut être joint sur {}"
        return ans.format(self.name, self.surname, self.birth_date, self.email)

