#!/usr/bin/python3
# -*- coding: utf-8 -*-


def sort_courses(student_courses):
	courses_students = []
	for student, course in student_courses:
		courses_students.append((course, student))
	return sorted(courses_students)

@@q1@@
